/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cuantaclicks;

/**
 *
 * @author Olivera
 */
public class Contador extends javax.swing.JFrame {
    int contador = 0;
    String letra = "0";
   

    /**
     * Creates new form Contador
     */
    public Contador() {
        initComponents();
        editableContador.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaClicks = new javax.swing.JLabel();
        editableContador = new javax.swing.JTextField();
        botonAumentar = new javax.swing.JButton();
        botonDisminuir = new javax.swing.JButton();
        botonReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));

        etiquetaClicks.setBackground(new java.awt.Color(255, 255, 255));
        etiquetaClicks.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        etiquetaClicks.setForeground(new java.awt.Color(255, 102, 51));
        etiquetaClicks.setText("PUNTOS");

        editableContador.setBackground(new java.awt.Color(204, 255, 255));
        editableContador.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        editableContador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        editableContador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editableContadorActionPerformed(evt);
            }
        });
        editableContador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                editableContadorKeyTyped(evt);
            }
        });

        botonAumentar.setBackground(new java.awt.Color(51, 153, 0));
        botonAumentar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonAumentar.setForeground(new java.awt.Color(204, 204, 204));
        botonAumentar.setText("Aumentar");
        botonAumentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAumentarActionPerformed(evt);
            }
        });

        botonDisminuir.setBackground(new java.awt.Color(204, 51, 0));
        botonDisminuir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonDisminuir.setForeground(new java.awt.Color(204, 204, 204));
        botonDisminuir.setText("Disminuir");
        botonDisminuir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDisminuirActionPerformed(evt);
            }
        });

        botonReset.setBackground(new java.awt.Color(153, 0, 153));
        botonReset.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonReset.setForeground(new java.awt.Color(204, 204, 204));
        botonReset.setText("Reset");
        botonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(editableContador, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonReset, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(botonAumentar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonDisminuir))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(etiquetaClicks)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiquetaClicks)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editableContador, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAumentar)
                    .addComponent(botonDisminuir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonReset)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editableContadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editableContadorKeyTyped
        // TODO add your handling code here:
            evt.consume();
    }//GEN-LAST:event_editableContadorKeyTyped

    private void botonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonResetActionPerformed
        // TODO add your handling code here:
        contador = 0;
        editableContador.setText("0");
    }//GEN-LAST:event_botonResetActionPerformed

    private void botonAumentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAumentarActionPerformed
        // TODO add your handling code here:
        contador++;
        letra = Integer.toString(contador);
        editableContador.setText(letra);
    }//GEN-LAST:event_botonAumentarActionPerformed

    private void botonDisminuirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDisminuirActionPerformed
        // TODO add your handling code here:
        contador--;
        letra = Integer.toString(contador);
        editableContador.setText(letra);
    }//GEN-LAST:event_botonDisminuirActionPerformed

    private void editableContadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editableContadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editableContadorActionPerformed

  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAumentar;
    private javax.swing.JButton botonDisminuir;
    private javax.swing.JButton botonReset;
    private javax.swing.JTextField editableContador;
    private javax.swing.JLabel etiquetaClicks;
    // End of variables declaration//GEN-END:variables
}
