/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;
/**
 *
 * @author Olivera
 */
import Controlador.CarreraModelo;
import Modelo.Carrera;
import java.util.ArrayList;
import parcial3.*;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


public class Plataforma extends javax.swing.JFrame {


     private ArrayList<Carrera> estudiantes;
     private CarreraModelo tabla;
     
     
     

    public Plataforma() {
        estudiantes = new ArrayList();
        tabla = new CarreraModelo(estudiantes);
        tabla.fireTableDataChanged();
        initComponents();

        setLocationRelativeTo(null);
        setTitle("Plataforma");
        
        
        ((JPanel)getContentPane()).setOpaque(fal­se); 
        
     
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaListado = new javax.swing.JTable();
        menuBar = new javax.swing.JMenuBar();
        menuBarSistema = new javax.swing.JMenu();
        menuItemUsuarios = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuItemSalir = new javax.swing.JMenuItem();
        menuBarExamen = new javax.swing.JMenu();
        menuItemCrear = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuItemModificar = new javax.swing.JMenuItem();
        menuBarAlumnos = new javax.swing.JMenu();
        menuItemContestar = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menuItemVer = new javax.swing.JMenuItem();
        menuBarAyuda = new javax.swing.JMenu();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        menuItemAcercaDe = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaListado.setBackground(new java.awt.Color(0, 204, 255));
        tablaListado.setFont(new java.awt.Font("Century Gothic", 2, 18)); // NOI18N
        tablaListado.setModel(tabla);
        jScrollPane1.setViewportView(tablaListado);

        menuBarSistema.setBackground(new java.awt.Color(153, 255, 255));
        menuBarSistema.setText("Sistema");

        menuItemUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        menuItemUsuarios.setFont(new java.awt.Font("Century Schoolbook", 0, 15)); // NOI18N
        menuItemUsuarios.setText("Usuarios");
        menuBarSistema.add(menuItemUsuarios);
        menuBarSistema.add(jSeparator1);

        menuItemSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        menuItemSalir.setFont(new java.awt.Font("Century Schoolbook", 0, 15)); // NOI18N
        menuItemSalir.setText("Salir");
        menuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSalirActionPerformed(evt);
            }
        });
        menuBarSistema.add(menuItemSalir);

        menuBar.add(menuBarSistema);

        menuBarExamen.setBackground(new java.awt.Color(153, 255, 255));
        menuBarExamen.setText("Examen");

        menuItemCrear.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        menuItemCrear.setFont(new java.awt.Font("Century Schoolbook", 0, 15)); // NOI18N
        menuItemCrear.setText("Crear");
        menuItemCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCrearActionPerformed(evt);
            }
        });
        menuBarExamen.add(menuItemCrear);
        menuBarExamen.add(jSeparator2);

        menuItemModificar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        menuItemModificar.setFont(new java.awt.Font("Century Schoolbook", 0, 15)); // NOI18N
        menuItemModificar.setText("Modificar");
        menuItemModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemModificarActionPerformed(evt);
            }
        });
        menuBarExamen.add(menuItemModificar);

        menuBar.add(menuBarExamen);

        menuBarAlumnos.setBackground(new java.awt.Color(153, 255, 255));
        menuBarAlumnos.setText("Alumnos");

        menuItemContestar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        menuItemContestar.setFont(new java.awt.Font("Century Schoolbook", 0, 15)); // NOI18N
        menuItemContestar.setText("Contestar");
        menuBarAlumnos.add(menuItemContestar);
        menuBarAlumnos.add(jSeparator3);

        menuItemVer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        menuItemVer.setFont(new java.awt.Font("Century Schoolbook", 0, 15)); // NOI18N
        menuItemVer.setText("Ver calificaciones");
        menuBarAlumnos.add(menuItemVer);

        menuBar.add(menuBarAlumnos);

        menuBarAyuda.setBackground(new java.awt.Color(153, 0, 51));
        menuBarAyuda.setText("Ayuda");
        menuBarAyuda.add(jSeparator4);

        menuItemAcercaDe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        menuItemAcercaDe.setFont(new java.awt.Font("Century Schoolbook", 0, 15)); // NOI18N
        menuItemAcercaDe.setText("Acerca de...");
        menuItemAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAcercaDeActionPerformed(evt);
            }
        });
        menuBarAyuda.add(menuItemAcercaDe);

        menuBar.add(menuBarAyuda);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 836, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuItemSalirActionPerformed

    private void menuItemCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCrearActionPerformed
        Examenes ver = new Examenes(this, true);
        ver.setoEstudiantes(estudiantes);
        ver.setVisible(true);
        tabla.fireTableDataChanged();
    }//GEN-LAST:event_menuItemCrearActionPerformed

    private void menuItemModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemModificarActionPerformed
      
    }//GEN-LAST:event_menuItemModificarActionPerformed

    private void menuItemAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAcercaDeActionPerformed
       AcercaDe chido = new AcercaDe (this, true);
       chido.setVisible(true);
    }//GEN-LAST:event_menuItemAcercaDeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Plataforma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Plataforma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Plataforma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Plataforma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Plataforma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuBarAlumnos;
    private javax.swing.JMenu menuBarAyuda;
    private javax.swing.JMenu menuBarExamen;
    private javax.swing.JMenu menuBarSistema;
    private javax.swing.JMenuItem menuItemAcercaDe;
    private javax.swing.JMenuItem menuItemContestar;
    private javax.swing.JMenuItem menuItemCrear;
    private javax.swing.JMenuItem menuItemModificar;
    private javax.swing.JMenuItem menuItemSalir;
    private javax.swing.JMenuItem menuItemUsuarios;
    private javax.swing.JMenuItem menuItemVer;
    private javax.swing.JTable tablaListado;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the tabla
     */
    public CarreraModelo getTabla() {
        return tabla;
    }

    /**
     * @param tabla the tabla to set
     */
    public void setTabla(CarreraModelo tabla) {
        this.tabla = tabla;
    }
    public boolean Actualizar(){
         tabla.fireTableDataChanged();
         return true;
         
     }
}
