/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

import Modelo.Carrera;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;

/**
 *
 * @author Olivera
 */
public class Preguntas extends javax.swing.JDialog {

   private ArrayList<Carrera> aEstudiantes;
   private ArrayList<Examenes> Examen;
   
    public Preguntas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        aEstudiantes = new ArrayList();
        initComponents();
        
        
        setLocationRelativeTo(null);
        setTitle("Elaborar Examen");
        ((JPanel)getContentPane()).setOpaque(fal­se); 
        ImageIcon uno=new ImageIcon(this.getClass().getResource("/Imagenes/Plataforma.png")); 
        JLabel fondo= new JLabel(); 
        fondo.setIcon(uno); 
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER); 
        fondo.setBounds(0,0,uno.getIconWidth(),u­no.getIconHeight());
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaPregunta = new javax.swing.JLabel();
        etiquetaCorrecta = new javax.swing.JLabel();
        etiquetaIncorrecta = new javax.swing.JLabel();
        etiquetaIncorrecta2 = new javax.swing.JLabel();
        etiquetaIncorrecta3 = new javax.swing.JLabel();
        editablePregunta = new javax.swing.JTextField();
        editableCorrecta = new javax.swing.JTextField();
        editableIncorrecta = new javax.swing.JTextField();
        editableIncorrecta2 = new javax.swing.JTextField();
        editableIncorrecta3 = new javax.swing.JTextField();
        botonCancelar = new javax.swing.JButton();
        botonAnterior = new javax.swing.JButton();
        botonSiguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        etiquetaPregunta.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        etiquetaPregunta.setText("Pregunta");

        etiquetaCorrecta.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        etiquetaCorrecta.setText("Correcta");

        etiquetaIncorrecta.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        etiquetaIncorrecta.setText("Incorrecta");

        etiquetaIncorrecta2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        etiquetaIncorrecta2.setText("Incorrecta");

        etiquetaIncorrecta3.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        etiquetaIncorrecta3.setText("Incorrecta");

        editablePregunta.setBackground(new java.awt.Color(51, 255, 255));
        editablePregunta.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        editableCorrecta.setBackground(new java.awt.Color(0, 204, 0));
        editableCorrecta.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        editableIncorrecta.setBackground(new java.awt.Color(204, 51, 0));
        editableIncorrecta.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        editableIncorrecta2.setBackground(new java.awt.Color(204, 51, 0));
        editableIncorrecta2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        editableIncorrecta3.setBackground(new java.awt.Color(204, 51, 0));
        editableIncorrecta3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        botonCancelar.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        botonCancelar.setForeground(new java.awt.Color(255, 153, 0));
        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonAnterior.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        botonAnterior.setForeground(new java.awt.Color(153, 0, 51));
        botonAnterior.setText("Anterior");
        botonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAnteriorActionPerformed(evt);
            }
        });

        botonSiguiente.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        botonSiguiente.setForeground(new java.awt.Color(0, 204, 51));
        botonSiguiente.setText("Siguiente ");
        botonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(etiquetaCorrecta)
                                    .addComponent(etiquetaPregunta))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(editablePregunta, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                                    .addComponent(editableCorrecta)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(etiquetaIncorrecta2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                        .addComponent(editableIncorrecta2, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(etiquetaIncorrecta)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(editableIncorrecta, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(etiquetaIncorrecta3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(editableIncorrecta3, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(botonCancelar)
                        .addGap(105, 105, 105)
                        .addComponent(botonAnterior)
                        .addGap(137, 137, 137)
                        .addComponent(botonSiguiente)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar)
                    .addComponent(botonAnterior)
                    .addComponent(botonSiguiente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaPregunta)
                    .addComponent(editablePregunta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaCorrecta)
                    .addComponent(editableCorrecta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaIncorrecta)
                    .addComponent(editableIncorrecta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaIncorrecta2)
                    .addComponent(editableIncorrecta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editableIncorrecta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaIncorrecta3))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        this.setVisible(false);
        
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnteriorActionPerformed
        this.setVisible(false);
        Examenes regresa = new Examenes(null, true);
        regresa.setVisible(true);
    }//GEN-LAST:event_botonAnteriorActionPerformed

    private void botonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiguienteActionPerformed
         
         
    }//GEN-LAST:event_botonSiguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Preguntas dialog = new Preguntas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAnterior;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonSiguiente;
    private javax.swing.JTextField editableCorrecta;
    private javax.swing.JTextField editableIncorrecta;
    private javax.swing.JTextField editableIncorrecta2;
    private javax.swing.JTextField editableIncorrecta3;
    private javax.swing.JTextField editablePregunta;
    private javax.swing.JLabel etiquetaCorrecta;
    private javax.swing.JLabel etiquetaIncorrecta;
    private javax.swing.JLabel etiquetaIncorrecta2;
    private javax.swing.JLabel etiquetaIncorrecta3;
    private javax.swing.JLabel etiquetaPregunta;
    // End of variables declaration//GEN-END:variables
}
